version: "3.9"

services:
  monitor-shell:
    image: monitoring-shell
    container_name: monitor-shell
    environment:
      - timeinterval=5
    volumes:
      - ./app:/app
    restart: always

  backup-python:
    image: backup-python
    container_name: backup-python
    environment:
      - CHECKFORBACKUP=5
      - BACKUPDIR=/app/backup
    volumes:
      - ./app:/app
    depends_on:
      - monitor-shell
    restart: always
